<?php /* this script is generated by soyshop. */
function soyshop_footer($html,$htmlObj){

ob_start();

echo <<<HTML
<div id="footer_navi">
  <ul>
    <!--li><a href="">ご利用ガイド</a></li-->
    <li><a href="@@SOYSHOP_URI@@/question.html">よくあるご質問</a></li>
    <li><a href="@@SOYSHOP_URI@@/exchange.html">特定商取引法に基づく表記</a></li>
    <li><a href="@@SOYSHOP_URI@@/policy.html">プライバシーポリシー</a></li>
  </ul>
</div>
HTML;

ob_end_flush();

}
?>