<?php /* this script is generated by soyshop. */
function soyshop_method($html,$htmlObj){

ob_start();

echo <<<HTML
<div class="footer_column">
  <section>
    <h1>配送料金について</h1>
    <p>お買い物の合計金額が○○○円以上で送料無料となります。<br>
      それ以下のお買い物の場合の配送料金は<a href="#">こちら</a>をご覧ください。</p>
  </section>
      
  <section>
    <h1>商品の到着について</h1>
    <p>ご注文いただいてから5営業日以内に発送いたします。</p>
  </section>
</div>
HTML;

ob_end_flush();

}
?>