<?php /* this script is generated by soyshop. */
function soyshop_navi($html,$htmlObj){

ob_start();

echo <<<HTML
<ul>
  <!--li><a href="#">ご利用ガイド</a></li-->
  <li><a href="@@SOYSHOP_URI@@/question.html">よくあるご質問</a></li>
  <li><a href="@@SOYSHOP_URI@@/inquiry.html">お問い合わせ</a></li>
</ul>
HTML;

ob_end_flush();

}
?>