<?php /* this script is generated by soyshop. */
function soyshop_payment($html,$htmlObj){

ob_start();

echo <<<HTML
<div class="footer_column">

  <section>
    <h1>お支払いについて</h1>
    <dl>
      <dt>
        <h2>代金引換</h2>
      </dt>
      <dd>説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト</dd>

      <dt>
        <h2>銀行振込</h2>
      </dt>
      <dd>説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト</dd>
      <dt>
        <h2>クレジットカード</h2>
      </dt>

      <dd>説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト</dd>
      <dt>
        <h2>コンビニ決済</h2>
      </dt>
      <dd>説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト説明テキスト</dd>
    </dl>
  </section>

</div>
HTML;

ob_end_flush();

}
?>