<?php /* this script is generated by soyshop. */
function soyshop_shop_info($html,$htmlObj){

ob_start();

echo <<<HTML
<div class="footer_column">

  <section>
    <h1>ショップ情報</h1>
    <h2>@@SOYSHOP_NAME@@</h2>
    <p>TEL：075-123-456<br>
      FAX：075-123-457<br>
      営業時間：10:00?18:00<br>

    定休日：水・日・祝日</p>
    <p>定休日にいただいたご注文やご質問へのお返事は、翌営業日<br>
      以降のお返事となりますのでご了承ください。<br>
      ご注文は24時間受け付けております。</p>
  </section>
</div>
HTML;

ob_end_flush();

}
?>