<?php

class EditorPage extends CMSWebPageBase{
	
	private $moduleId;
	private $modulePath;
	private $iniPath;
	
	function doPost(){
		if(soy2_check_token()){
			$edit = $_POST["Edit"];
			
			//make ini
			$array = array();
			$array[] = "name=" . $edit["name"];
			$array[] = "content=" . rawurlencode($edit["content"]);
			
			file_put_contents($this->iniPath, implode("\n", $array));
			
			$funcName = str_replace(".", "_", substr($this->moduleId, strpos($this->moduleId, ".")));
			
			//make php
			$array = array();
			$array[] = "<?php /* this script is generated by soyshop. */";
			$array[] = "function soycms_" . $funcName . '($html,$htmlObj){';
			$array[] = "";
			$array[] = "ob_start();";
			$array[] = "";
			$array[] = "echo <<<HTML";
			$array[] = trim($edit["content"]);
			$array[] = "HTML;";
			$array[] = "";
			$array[] = "ob_end_flush();"; 
			$array[] = "";
			$array[] = "}";
			$array[] = "?>";
			file_put_contents($this->modulePath, implode("\n", $array));
		}

		$this->jump("Module.HTML.Editor?moduleId=" . $_GET["moduleId"]);
	}
	
	function EditorPage(){
		$this->moduleId = (isset($_GET["moduleId"])) ? htmlspecialchars(str_replace("/", ".", $_GET["moduleId"])) : null;

		$moduleDir = self::getModuleDirectory();
		
		$this->modulePath = $moduleDir . str_replace(".", "/", $this->moduleId) . ".php";
		$this->iniPath =$moduleDir . str_replace(".", "/", $this->moduleId) . ".ini";

		WebPage::WebPage();
		
		$ini = @parse_ini_file($this->iniPath);

		$this->addForm("form");
		
		$this->addLabel("module_name_text", array(
			"text" => (isset($ini["name"])) ? $ini["name"] : $this->moduleId
		));
		
		$this->addInput("module_name", array(
			"name" => "Edit[name]",
			"value" => (isset($ini["name"])) ? $ini["name"] : $this->moduleId,
			"style" => "padding: 3px; width:300px;"
		));

		$this->addLabel("module_id", array(
			"text" => $this->moduleId
		));

		$content = (isset($ini["content"])) ? $ini["content"] : ""; 
		$this->addTextArea("module_content", array(
			"name" => "Edit[content]",
			"value" => $this->getModuleContent($content, file_get_contents($this->modulePath)),
			"style" => "width: 800px !important;height:500px !important;"
		));
		
		$this->addLabel("module_example", array(
			"text" => "<!-- cms:module=\"html." . $this->moduleId."\" -->\n" . @$ini["name"] . "のモジュールを読み込みます。\n<!-- /cms:module=\"html." . $this->moduleId."\" -->",
			"style" => "width:600px;height:80px;"
		));
	}
	
	private function getModuleContent($ini, $str){
		if(strlen($ini) > 0){
			preg_match('/<<<HTML(.*)HTML;/s', $str, $match);
			return (isset($match[1])) ? trim($match[1]) : "";
		}
		
		$array = array();				
		return implode("\n", $array);
	}
	
	private function getModuleDirectory(){
		return UserInfoUtil::getSiteDirectory() . ".module/html/";
	}
}
?>