<?php /* this script is generated by soyshop. */
function soyshop_header_navigation($html,$htmlObj){

ob_start();

echo <<<HTML
<h1>おいしい野菜をみなさんにお届けします！</h1>
<ul>
	<li><a href="@@SOYSHOP_URI@@/concept.html">会社概要</a></li>
	<li><a href="@@SOYSHOP_URI@@/question.html">よくあるご質問</a></li>
</ul>
HTML;

ob_end_flush();

}
?>