<?php /* this script is generated by soyshop. */
function soyshop_search_query($html,$htmlObj){
	ob_start();
?><?php
//ここにモジュールとして読み込むHTML・PHPを記述してください。
//使用可能な変数
//     $html	テンプレートに記述されたHTML
//     $htmlObj	ページオブジェクト($htmlObj->createAdd()が使えます)

$html = array();

SOY2::import("module.plugins.custom_search_field.util.CustomSearchFieldUtil");
$params = CustomSearchFieldUtil::getParameter("c_search");

$config = CustomSearchFieldUtil::getConfig();
$keys = (is_array($params) && count($params)) ? array_keys($params) : array();
if(count($keys)){
	for($i = 0; $i < count($keys); $i++){
		$csfId = $keys[$i];
		$v = (isset($params[$csfId])) ? $params[$csfId] : null;

		//文字列の場合の処理
		if(!is_array($v)){
			$v = htmlspecialchars(trim($v), ENT_QUOTES, "UTF-8");
			if(!strlen($v)) continue;

			if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
				$html[] =  "<li>" . $config[$csfId]["label"] . "：" . $v . "</li>";
				continue;
			}

			//商品名
			if($csfId == "item_name" && strlen($v)){
				$html[] = "<li>商品名：" . $v . "</li>";
			}


			//価格
			if(strpos($csfId, "_min")){
				$max = (int)$_GET["c_search"]["item_price_max"];
				$max = ($max > 0) ? soy2_number_format($max) : "";
				$html[] = "<li>商品価格：" . number_format((int)$v) . "〜" . $max . "</li>";
				$i++;
				continue;
			}else if(strpos($csfId, "_max")){
				$html[] = "<li>商品価格：0〜" . number_format((int)$v) . "</li>";
				continue;
			}

			//最小
			if(strpos($csfId, "_start")){
				$csfId = str_replace("_start", "", $csfId);
				if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
					$end = (int)$_GET["c_search"][$csfId . "_end"];
					$end = ($end > 0) ? soy2_number_format($end) : "";
					$html[] = "<li>" . $config[$csfId]["label"] . "：" . $v . "〜" . $end . "</li>";

				}
				$i++;
				continue;
			}else if(strpos($csfId, "_end")){
				$csfId = str_replace("_end", "", $csfId);
				if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
					$html[] = "<li>" . $config[$csfId]["label"] . "：0〜" . $v . "</li>";
				}
			}
		}else{
			if(!count($v)) continue;

			$arr = array();
			foreach($v as $val){
				if(!strlen(trim($val))) continue;
				$arr[] = $val;
			}

			if(!count($arr)) continue;

			if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
				$html[] = "<li>" . $config[$csfId]["label"] . "：" . implode(",", $arr) . "</li>";
			}
		}
	}
}
echo implode("\n", $html);
?><?php
	ob_end_flush();
}
?>
