<?php /* this script is generated by soyshop. */
function soyshop_address($html,$htmlObj){

ob_start();

echo <<<HTML
<address> Copyright (c) お豆商事種式会社 All Rights Reserved.<br />
 Powered by <a href="http://www.soycms.net/">SOY CMS</a> and <a href="http://www.soyshop.net/">SOY Shop </a></address>
HTML;

ob_end_flush();

}
?>