<?php /* this script is generated by soyshop. */
function soyshop_footer($html,$htmlObj){

ob_start();

echo <<<HTML
<ul>
	<li><a href="@@SOYSHOP_URI@@">トップページ</a></li>
	<li><a href="@@SOYSHOP_URI@@/item/list/">商品一覧</a></li>
	<li><a href="@@SOYSHOP_URI@@/delivery.html">お支払・配送について</a></li>
	<li><a href="@@SOYSHOP_URI@@/concept.html">会社概要</a></li>
	<li><a href="@@SOYSHOP_URI@@/inquiry.html">お問い合わせ</a></li>
</ul>
<ul>
	<li><a href="@@SOYSHOP_URI@@/exchange.html">特定商取引法に関する表示</a></li>
	<li><a href="@@SOYSHOP_URI@@/policy.html">プライバシーポリシー</a></li>
</ul><!-- フッターのリンク集が入ります /-->
HTML;

ob_end_flush();

}
?>