<?php /* this script is generated by soyshop. */
function soyshop_global_navigation($html,$htmlObj){

ob_start();

echo <<<HTML
<ul class="clearfix">
	<li><a href="@@SOYSHOP_URI@@">トップページ</a></li>
	<li><a href="@@SOYSHOP_URI@@/item/list/">商品一覧</a></li>
	<li><a href="@@SOYSHOP_URI@@/delivery.html">お支払・配送について</a></li>
	<li><a href="@@SOYSHOP_URI@@/user/top">マイページ</a></li>
</ul><!-- ナビゲーションが入ります -->
HTML;

ob_end_flush();

}
?>