<?php /* this script is generated by soyshop. */
function soyshop_header($html,$htmlObj){

ob_start();

echo <<<HTML
<h2><img src="@@SOYSHOP_URI@@/themes/shop/logo.jpg" alt="お豆商事種式会社" height="77" width="560" /></h2>
<p><a href="@@SOYSHOP_URI@@/cart"><img src="@@SOYSHOP_URI@@/themes/shop/look_cart.jpg" alt="カートの中を見る" class="wink" height="44" width="202" /></a></p>
HTML;

ob_end_flush();

}
?>