<?php /* this script is generated by soyshop. */
function soyshop_search_box($html,$htmlObj){

ob_start();

echo <<<HTML
<form method="GET" action="@@SOYSHOP_URI@@/search.html">
	<p>
		<input type="hidden" name="type" value="name">
		<input id="textfield" type="text" name="q" />
		<br>
		<input type="image" name="button" id="button" value="検索" src="@@SOYSHOP_URI@@/themes/shop/side_search_btn.jpg" />
	</p>
</form>
HTML;

ob_end_flush();

}
?>