ALTER TABLE soyshop_category MODIFY COLUMN category_alias VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE soyshop_category MODIFY COLUMN category_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_category MODIFY COLUMN category_is_open TINYINT NOT NULL DEFAULT 1;
