CREATE TABLE soyboard_thread(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  page_id INTEGER,
  title VARCHAR(255) NOT NULL,
  owner VARCHAR(64) NOT NULL,
  cdate DATE NOT NULL,
  lastsubmitdate DATETIME NOT NULL,
  sort_date DATE NOT NULL,
  readonly INTEGER
)ENGINE=InnoDB;


CREATE TABLE soyboard_response(
	thread_id INTEGER NOT NULL,
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	submitdate DATETIME NOT NULL,
	hash VARCHAR(32) NOT NULL,
	body VARCHAR(1024) NOT NULL,
	host VARCHAR(32) NOT NULL,
	response_id INTEGER NOT NULL DEFAULT 0
)ENGINE=InnoDB;


CREATE TABLE soyboard_config(
	thread_id INTEGER NOT NULL PRIMARY KEY,
	show_host INTEGER NOT NULL DEFAULT 0,
	default_name VARCHAR(64) NOT NULL,
	is_stopped INTEGER NOT NULL DEFAULT 0,
	max_response INTEGER NOT NULL DEFAULT 1000,
	sage_accept INTEGER NOT NULL DEFAULT 1
)ENGINE=InnoDB;