<?php /* this script is generated by soyshop. */
function soyshop_copyright($html,$htmlObj){

ob_start();

echo <<<HTML
<p><small>Copyright &copy; @@SOYSHOP_NAME@@, All Rights Reserved.</small></p>
HTML;

ob_end_flush();

}
?>