<?php /* this script is generated by soyshop. */
function soycms_search_query($html,$htmlObj){
	ob_start();
?><?php
//ここにモジュールとして読み込むHTML・PHPを記述してください。
//使用可能な変数
//     $html	テンプレートに記述されたHTML
//     $htmlObj	ページオブジェクト($htmlObj->createAdd()が使えます)

$html = array();

SOY2::import("site_include.plugin.CustomSearchField.util.CustomSearchFieldUtil");
$config = CustomSearchFieldUtil::getConfig();

$q = CustomSearchFieldUtil::getParameter("q");
$params = CustomSearchFieldUtil::getParameter("c_search");

$keys = (is_array($params) && count($params)) ? array_keys($params) : array();
if(is_string($q) && strlen($q)) $keys[] = "q";
if(count($keys)){
	for($i = 0; $i < count($keys); $i++){
		$csfId = $keys[$i];
		$v = ($csfId == "q") ? $q : $params[$csfId];

		//文字列の場合の処理
		if(!is_array($v)){
			$v = htmlspecialchars(trim($v), ENT_QUOTES, "UTF-8");
			if(!strlen($v)) continue;

			if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
				$html[] =  "<li>" . $config[$csfId]["label"] . "：" . $v . "</li>";
				continue;
			}

			//記事名
			if($csfId == "q"){
				$html[] = "<li>記事検索：" . $v . "</li>";
			}

			//最小
			if(strpos($csfId, "_start")){
				$csfId = str_replace("_start", "", $csfId);
				if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
					$end = (int)$params[$csfId . "_end"];
					$end = ($end > 0) ? soy2_number_format($end) : "";
					$html[] = "<li>" . $config[$csfId]["label"] . "：" . $v . "〜" . $end . "</li>";

				}
				$i++;
				continue;
			}else if(strpos($csfId, "_end")){
				$csfId = str_replace("_end", "", $csfId);
				if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
					$html[] = "<li>" . $config[$csfId]["label"] . "：0〜" . $v . "</li>";
				}
			}
		}else{
			if(!count($v)) continue;

			$arr = array();
			foreach($v as $val){
				if(!strlen(trim($val))) continue;
				$arr[] = $val;
			}

			if(!count($arr)) continue;

			if(isset($config[$csfId]) && strlen($config[$csfId]["label"])){
				$html[] = "<li>" . $config[$csfId]["label"] . "：" . implode(",", $arr) . "</li>";
			}
		}
	}
}
echo implode("\n", $html);
?><?php
	ob_end_flush();
}
?>
