<?php /* this script is generated by soyshop. */
function soyshop_copyright(string $html, HTMLPage $htmlObj){

return <<<HTML
<p><small>Copyright &copy; @@SOYSHOP_NAME@@, All Rights Reserved.</small></p>
HTML;

}
?>
