<?php /* this script is generated by soyshop. */
function soyshop_header(string $html, HTMLPage $htmlObj){

return <<<HTML
<hgroup>
  <h1><a href="@@SOYSHOP_URI@@">@@SOYSHOP_NAME@@</a></h1>
  <h2>国産からインポートまで、店長絶賛のインテリア小物、家具、雑貨まで</h2>
</hgroup>
HTML;

}
?>
