<?php
/**
 * @class Payment_methodList
 * @generated by SOY2HTML
 */
SOYShopPlugin::load("soyshop.payment");
class PaymentMethodListComponent extends HTMLList{

	private $selected;
	private $cart;

	protected function populateItem($entity, $key, $counter, $length){
		$this->addCheckBox("payment_method", array(
			"name" => "payment_module",
			"value" => $key,
			"selected" => ( ($this->selected == $key) || ($length == 1) ),
			"label" => MessageManager::get("LABEL_SELECT")
		));

		$this->addLabel("payment_name", array(
			"text" => $entity["name"],
		));

		$this->addLabel("payment_description", array(
			"html" => $entity["description"]
		));

		$this->addModel("is_payment_charge", array(
			"visible" => (isset($entity["price"]) && (int)$entity["price"] > 0)
		));

		$this->addLabel("payment_charge", array(
			"text" => (isset($entity["price"])) ? MessageManager::get("LABEL_PRICE", array("price" => soy2_number_format($entity["price"]))) : "",
		));

		//falseを返すことができる拡張ポイント
		return SOYShopPlugin::invoke("soyshop.payment", array("mode" => "method", "moduleId" => $key, "cart" => $this->getCart()))->getMethod();
	}

	function getSelected() {
		return $this->selected;
	}
	function setSelected($selected) {
		if(strlen($selected)){
			$this->selected = $selected;
		}
	}

	function getCart(){
		return $this->cart;
	}
	function setCart($cart){
		$this->cart = $cart;
	}
}
