<?php
/**
 * @class Payment_methodList
 * @generated by SOY2HTML
 */
class PaymentMethodListComponent extends HTMLList{

	private $selected;

	protected function populateItem($entity, $key, $counter, $length){
		$this->addCheckBox("payment_method", array(
			"name" => "payment_module",
			"value" => $key,
			"selected" => ( ($this->selected == $key) || ($length == 1) ),
			"label" => MessageManager::get("LABEL_SELECT")
		));

		$this->addLabel("payment_name", array(
			"text" => $entity["name"],
		));

		$this->addLabel("payment_description", array(
			"html" => $entity["description"]
		));

		$this->addLabel("payment_charge", array(
			"text" => strlen($entity["price"]) ? MessageManager::get("LABEL_PRICE", array("price" => number_format($entity["price"]))) : "",
		));
	}

	function getSelected() {
		return $this->selected;
	}
	function setSelected($selected) {
		if(strlen($selected)){
			$this->selected = $selected;
		}
	}
}
?>