var advanced_textarea=function(a){this.$=a;var b=a.get(0);b.inst=this;this.insertHTML=function(a){if(null!=document.selection)b.focus(),b.selection=document.selection.createRange(),b.selection.text=a;else{var c=b.selectionStart,d=b.selectionEnd,e=b.value.substring(0,c),d=b.value.substring(d),f=b.scrollTop,g=b.scrollLeft;b.value=e+a+d;b.scrollTop=f;b.scrollLeft=g;b.setSelectionRange(c,c+a.length);b.focus()}};this.insertTab=function(a){if(null!=document.selection){b.selection=document.selection.createRange();
var c=b.selection.text;0==b.selection.compareEndPoints("StartToEnd",b.selection)?b.selection.text=String.fromCharCode(9):(a.shiftKey?(c=c.replace(/\n\t/g,"\n"),"\t"==c.substr(0,1)&&(c=c.substr(1,c.length-1)+"\n")):(c=c.replace(/\n/g,"\n\t"),c="\t"+c+"\n"),b.selection.text=c)}else{var d=b.selectionStart;c=b.selectionEnd;var e=b.scrollTop,f=b.value.substring(0,d),g=b.value.substring(c);d==c?(b.value=f+"\t"+g,b.scrollTop=e,b.setSelectionRange(d+1,d+1)):(c=b.value.substring(d,c),a.shiftKey?(c=c.replace(/\n\t/g,
"\n"),"\t"==c.substr(0,1)&&(c=c.substr(1,c.length-1))):(c=c.replace(/\n/g,"\n\t"),c="\t"==c.substr(c.length-1,1)?"\t"+c.substr(0,c.length-2)+"\n":"\t"+c),b.value=f+c+g,b.scrollTop=e,b.setSelectionRange(d,d+c.length))}}};(function(a){a(document).ready(function(){var b=document;a("table.form_list").each(function(){var b=1,c=null,c=a(this).find("tbody")?a(this).find("tbody tr"):a(this).find("tr");c.each(function(){0==b%2&&a(this).addClass("odd");b++})});var h=function(b){a(b).val(a(b).attr("hint"));a(b).attr("old_color",a(b).css("color"));a(b).css("color","gray")};a("input[hint],textarea[hint]").each(function(){1>a(this).attr("hint").length||(1>a(this).val().length&&h(a(this)),a(this).bind("focus",function(){var b=
a(this);a(b).val("");a(b).css("color",a(b).attr("old_color"))}),a(this).bind("blur",function(){(a(this).val()==a(this).attr("hint")||1>a(this).val().length)&&h(a(this))}))});a("form").each(function(){a(this).bind("submit",function(){a(".default_text").each(function(){a(this).val("")})})});a(".validate").each(function(){var b=a(this);a(this).bind("blur",function(){if(1>b.val().length)return a("#"+b.attr("id")+"_error").show(),!1});a(this).bind("focus",function(){a("#"+b.attr("id")+"_error").hide()})});
a(".popup").each(function(){var c=a(this);a(this).find(".close").bind("click",function(){c.hide()});a(this).bind("close",function(){c.hide()});a(this).bind("popup",function(c,d){d||(d={});try{var g=Math.max(b.documentElement.scrollLeft,b.body.scrollLeft),e=Math.max(b.documentElement.scrollTop,b.body.scrollTop);d.width&&a(this).css("width",d.width);d.height&&a(this).css("height",d.height);var f=Math.floor((a(window).width()-a(this).width())/2+g),h=Math.floor((a(window).height()-a(this).height())/4+
e);a(this).css({top:h,left:f});a(this).show()}catch(k){alert(k)}})});a.extend(a.fn,{textarea:function(b){return new advanced_textarea(a(this))}});a(".editor").each(function(){a(this).keydown(function(b){return 9==b.keyCode?(a(this).textarea().insertTab(b),!1):!0})});setTimeout(function(){a(".success,.notice,.error").each(function(){a(this).hasClass("always")||a(this).fadeOut()})},
2E3)})})(jQuery);
var ChangeAccountInfo={id:null,image_info:null,showInfo:!0,popup:function(a){this.id=a;if(window.onPopup)window.onPopup();$("#account_form_el").trigger("popup",{width:640,height:480})}},OptionWindow={type:null,image_info:null,showInfo:!0,url:null,popup:function(a){this.type=a;void 0!=a&&0<a.length&&(url=location.href,url=url.replace("Detail",a),$("#option_window").prop("src",url));if(window.onPopup)window.onPopup();setTimeout(function(){$("#option_window_el").trigger("popup",{width:640,height:480})},
250)}};
