ALTER TABLE soyshop_user mail_address VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE soyshop_user user_code VARCHAR(54) NOT NULL UNIQUE;
ALTER TABLE soyshop_user MODIFY COLUMN mail_error_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN not_send TINYINT NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_error TINYINT NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_publish TINYINT NOT NULL DEFAULT 1;
ALTER TABLE soyshop_user MODIFY COLUMN is_disabled TINYINT NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_profile_display TINYINT NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN user_type INTEGER NOT NULL DEFAULT 10;
