var SOY2_DatePicker=function(){};
$.extend(SOY2_DatePicker,{date_pickers:[],show:function(a,b){b||(b={show_future:false});if(!a.date_picker){b=$.extend(b);a.date_picker=new SOY2_DatePicker;a.date_picker.init(a,this.date_pickers.length,b);this.date_pickers.push(a.date_picker)}a.date_picker.render();for(b=0;b<this.date_pickers.length;b++)a.date_picker.id!=this.date_pickers[b].id&&this.date_pickers[b].close()},hide:function(a){a.date_picker&&a.date_picker.close()},hideAll:function(){for(var a=0;a<this.date_pickers.length;a++)this.date_pickers[a].close()},check:function(a){a.date_picker&&
a.date_picker.check($(a).val())}});
$.extend(SOY2_DatePicker.prototype,{id:null,node:null,element:null,year:null,month:null,date:null,show_future:false,today:null,init:function(a,b,c){this.node=a;this.id="soy2_date_picker_"+b;$.extend(this,c);this.today=new Date},render:function(){if(!this.element)this.element=this.buildElement();this.element.css({left:$(this.node).position().left});this.element.show()},close:function(){if(this.element)return this.element.hide()},check:function(a){if(a.match(/\d{4}-\d{2}-\d{2}/)){a=a.split("-");this.setValue(a[0],
a[1]-1,a[2]);var b=this.date;$("#"+this.id+" .cell").each(function(){$(this).attr("date")==b&&$(this).addClass("selected")})}else $("#"+this.id+" .selected").removeClass("selected");return true},buildElement:function(){var a=$('<div class="soy2_date_picker"><table class="soy2_date_picker_table"><thead><tr class="month_select"><th colspan="7"><select class="month_select"></select><select class="year_select"></select></th></tr></thead><tbody><tr class="day_row"><th class="holiday_cell">Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th class="holiday_cell">Sat</th></tr></tbody><tfoot><tr class="next_prev"><th colspan="7"><a href="javascript:void(0);" class="prev_btn">&lt;Prev</a><a href="javascript:void(0);" class="today_btn">Today</a><a href="javascript:void(0);" class="next_btn">Next&gt;</a></th></tr></tfoot></tbody></table></div>');
a.attr("id",this.id);$(this.node).after(a);for(var b=this,c="",d=1;d<=12;d++)c+='<option value="'+(d-1)+'">'+d+"</option>";$("select.month_select",a).append(c);$("select.year_select",a).bind("change",function(){b.setValue($(this).val(),b.month)});c="";var f=this.show_future?this.today.getFullYear()+10:this.today.getFullYear();for(d=1990;d<=f+3;d++)c+='<option value="'+d+'">'+d+"</option>";$("select.year_select",a).append(c);$("select.month_select",a).bind("change",function(){b.setValue(b.year,$(this).val())});
$(".prev_btn",a).bind("click",function(){b.moveMonth(-1)});$(".next_btn",a).bind("click",function(){b.moveMonth(+1)});$(".today_btn",a).bind("click",function(){b.setValue(b.today)});this.parseValue();c=false;if($(this.node).val().match(/\d{4}-\d{2}-\d{2}/)){c=$(this.node).val().split("-");this.setValue(c[0],c[1]-1,c[2]);c=true}this.buildCalendar(true);if(c){var e=this.date;$("#"+this.id+" .cell").each(function(){$(this).attr("date")==e&&$(this).addClass("selected")})}return a},buildCalendar:function(a){var b=
1;if(a){var c=$("#"+this.id+" tbody");for(a=0;a<6;a++){var d=$("<tr>");d.addClass("week");d.addClass("row-"+a);for(var f=0;f<7;f++){var e=$("<td></td>");e.attr("id",this.id+"_cell_"+b);e.addClass("cell");if(f==0||f==6)e.addClass("holiday_cell");d.append(e);b++}c.append(d)}}c=(new Date(this.year,this.month,1)).getDay();d=new Date(this.year,this.month+1,0);f=d.getDate();e=1;var h=this.year,i=this.month;b=42;var j=this;for(a=1;a<=b;a++){var g=$("#"+this.id+"_cell_"+a);g.bind("click",function(){});if(a<=
c)g.html("");else if(e>f)g.html("");else{html='<a href="javascript:void(0);">'+e+"</a>";g.html(html);g.attr("date",e);$("#"+this.id+"_cell_"+a).bind("click",function(){j.selectValue(h,i,$(this).attr("date"));$(this).addClass("selected")});e++}}b=Math.floor((f+6-d.getDay()-1)/7);for(a=0;a<6;a++)a>b?$("#"+this.id+" .row-"+a).hide():$("#"+this.id+" .row-"+a).show()},parseValue:function(){$(this.node).val().length<1&&this.setValue(this.today)},selectValue:function(a,b,c){b=a instanceof Date?a:new Date(a,
b,c);this.year=b.getFullYear();this.month=b.getMonth();this.date=b.getDate();b=this.month+1;a=this.year;a+="-";a+=b<10?"0"+b:b;a+="-";a+=this.date<10?"0"+this.date:this.date;$(this.node).val(a);$("#"+this.id+" .selected").removeClass("selected")},setValue:function(a,b,c){c||(c=1);a=a instanceof Date?a:new Date(a,b,c);this.year=a.getFullYear();this.month=a.getMonth();this.date=a.getDate();this.buildCalendar();a=this.element;$("select.month_select",a).val(this.month);$("select.year_select",a).val(this.year);
!this.show_future&&this.year==this.today.getFullYear()&&this.month==this.today.getMonth()?$(".next_btn",a).hide():$(".next_btn",a).show();$(this.node).val().length>0&&this.selectValue(this.year,this.month,this.date)},moveMonth:function(a){this.setValue(this.year,a>0?this.month+1:this.month-1)},debug:function(){alert(this.year+"-"+(this.month+1)+"-"+this.date)}});
$(function(){$("input.date_picker_start,input.date_picker_end").bind("focus",function(){SOY2_DatePicker.show(this)});$("body").bind("click",function(a){$(a.target).hasClass("date_picker_start")||$(a.target).hasClass("date_picker_end")||$(a.target).parents().hasClass("soy2_date_picker")||SOY2_DatePicker.hideAll()});$("input.date_picker_start,input.date_picker_end").bind("keyup",function(){SOY2_DatePicker.check(this)})});
