ALTER TABLE soyshop_user mail_address VARCHAR NOT NULL UNIQUE;
ALTER TABLE soyshop_user user_code VARCHAR NOT NULL UNIQUE;
ALTER TABLE soyshop_user MODIFY COLUMN mail_error_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN not_send INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_error INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_publish INTEGER NOT NULL DEFAULT 1;
ALTER TABLE soyshop_user MODIFY COLUMN is_disabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN is_profile_display INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soyshop_user MODIFY COLUMN user_type INTEGER NOT NULL DEFAULT 10;
